
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __AppOption = LightSwitchApplication.AppOption

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class AppOption
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __AppOption, __AppOption.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the AppOption entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __AppOption))
            MyBase.New(entitySet)
            
            __AppOption.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppOption_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppOption_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property SMTPServer As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPServer)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPServer, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPServer_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPServer_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPServer_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property SMTPPort As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPPort)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPPort, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPort_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPort_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPort_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property SMTPUsername As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPUsername)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPUsername, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPUsername_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPUsername_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPUsername_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property SMTPPassword As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPPassword)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.SMTPPassword, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPassword_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPassword_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SMTPPassword_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ReportingServicesURL As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.ReportingServicesURL)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.ReportingServicesURL, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ReportingServicesURL_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ReportingServicesURL_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ReportingServicesURL_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub
        Public ReadOnly Property CreatedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.CreatedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub
        Public ReadOnly Property ModifiedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.ModifiedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __AppOption.DetailsClass.GetValue(Me, __AppOption.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __AppOption.DetailsClass.SetValue(Me, __AppOption.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __AppOption, _
                __AppOption.DetailsClass, _
                __AppOption.DetailsClass.IImplementation, _
                __AppOption.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __AppOption, __AppOption.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __AppOption, __AppOption.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __AppOption.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __AppOptionEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __AppOption, __AppOption.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __AppOption, __AppOption.DetailsClass).Entry( _
                    AddressOf __AppOption.DetailsClass.__AppOption_CreateNew, _
                    AddressOf __AppOption.DetailsClass.__AppOption_Created, _
                    AddressOf __AppOption.DetailsClass.__AppOption_AllowSaveWithErrors)
            Private Shared Function __AppOption_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __AppOption)) As __AppOption
                Return New __AppOption(es)
            End Function
            Private Shared Sub __AppOption_Created(e As __AppOption)
                e.AppOption_Created()
            End Sub
            Private Shared Function __AppOption_AllowSaveWithErrors(e As __AppOption) As Boolean
                Dim result As Boolean = False
                e.AppOption_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __AppOption, __AppOption.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __AppOption, __AppOption.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __AppOption.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __AppOption, __AppOption.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property SMTPServer As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.SMTPServer),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property SMTPPort As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.SMTPPort),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property SMTPUsername As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.SMTPUsername),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property SMTPPassword As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.SMTPPassword),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ReportingServicesURL As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.ReportingServicesURL),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AppOption.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte()))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property SMTPServer As String
                Shadows Property SMTPPort As String
                Shadows Property SMTPUsername As String
                Shadows Property SMTPPassword As String
                Shadows Property ReportingServicesURL As String
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __AppOption.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __AppOption.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __AppOption)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly SMTPServer As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "SMTPServer", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPServer_OnValueChanged)
                Private Shared Sub _SMTPServer_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._SMTPServer, sf)
                End Sub
                Private Shared Function _SMTPServer_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.SMTPServer_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _SMTPServer_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.SMTPServer_Validate(r)
                End Sub
                Private Shared Function _SMTPServer_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.SMTPServer
                End Function
                Private Shared Sub _SMTPServer_SetImplementationValue(d As __AppOption.DetailsClass, v As String)
                    d.ImplementationEntity.SMTPServer = v
                End Sub
                Private Shared Sub _SMTPServer_OnValueChanged(e As __AppOption)
                    e.SMTPServer_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly SMTPPort As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "SMTPPort", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPort_OnValueChanged)
                Private Shared Sub _SMTPPort_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._SMTPPort, sf)
                End Sub
                Private Shared Function _SMTPPort_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.SMTPPort_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _SMTPPort_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.SMTPPort_Validate(r)
                End Sub
                Private Shared Function _SMTPPort_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.SMTPPort
                End Function
                Private Shared Sub _SMTPPort_SetImplementationValue(d As __AppOption.DetailsClass, v As String)
                    d.ImplementationEntity.SMTPPort = v
                End Sub
                Private Shared Sub _SMTPPort_OnValueChanged(e As __AppOption)
                    e.SMTPPort_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly SMTPUsername As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "SMTPUsername", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPUsername_OnValueChanged)
                Private Shared Sub _SMTPUsername_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._SMTPUsername, sf)
                End Sub
                Private Shared Function _SMTPUsername_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.SMTPUsername_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _SMTPUsername_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.SMTPUsername_Validate(r)
                End Sub
                Private Shared Function _SMTPUsername_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.SMTPUsername
                End Function
                Private Shared Sub _SMTPUsername_SetImplementationValue(d As __AppOption.DetailsClass, v As String)
                    d.ImplementationEntity.SMTPUsername = v
                End Sub
                Private Shared Sub _SMTPUsername_OnValueChanged(e As __AppOption)
                    e.SMTPUsername_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly SMTPPassword As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "SMTPPassword", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._SMTPPassword_OnValueChanged)
                Private Shared Sub _SMTPPassword_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._SMTPPassword, sf)
                End Sub
                Private Shared Function _SMTPPassword_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.SMTPPassword_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _SMTPPassword_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.SMTPPassword_Validate(r)
                End Sub
                Private Shared Function _SMTPPassword_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.SMTPPassword
                End Function
                Private Shared Sub _SMTPPassword_SetImplementationValue(d As __AppOption.DetailsClass, v As String)
                    d.ImplementationEntity.SMTPPassword = v
                End Sub
                Private Shared Sub _SMTPPassword_OnValueChanged(e As __AppOption)
                    e.SMTPPassword_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ReportingServicesURL As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "ReportingServicesURL", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ReportingServicesURL_OnValueChanged)
                Private Shared Sub _ReportingServicesURL_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._ReportingServicesURL, sf)
                End Sub
                Private Shared Function _ReportingServicesURL_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.ReportingServicesURL_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ReportingServicesURL_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ReportingServicesURL_Validate(r)
                End Sub
                Private Shared Function _ReportingServicesURL_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.ReportingServicesURL
                End Function
                Private Shared Sub _ReportingServicesURL_SetImplementationValue(d As __AppOption.DetailsClass, v As String)
                    d.ImplementationEntity.ReportingServicesURL = v
                End Sub
                Private Shared Sub _ReportingServicesURL_OnValueChanged(e As __AppOption)
                    e.ReportingServicesURL_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __AppOption)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __AppOption.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __AppOption)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __AppOption.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __AppOption)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __AppOption.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __AppOption)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __AppOption.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AppOption.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte()).Data), d As __AppOption.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __AppOption) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __AppOption, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __AppOption.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __AppOption.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __AppOption)
                    e.RowVersion_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _SMTPServer As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _SMTPPort As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _SMTPUsername As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _SMTPPassword As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ReportingServicesURL As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AppOption, __AppOption.DetailsClass, Byte()).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
