
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Timesheet = LightSwitchApplication.Timesheet

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class Timesheet
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Timesheet, __Timesheet.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Timesheet entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Timesheet))
            MyBase.New(entitySet)
            
            __Timesheet.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Timesheet_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Timesheet_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __Timesheet.DetailsClass.SetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property DurationMins As Integer
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.DurationMins)
            End Get
            Set
                __Timesheet.DetailsClass.SetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.DurationMins, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub DurationMins_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub DurationMins_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub DurationMins_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub
        Public ReadOnly Property CreatedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.CreatedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub
        Public ReadOnly Property ModifiedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.ModifiedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __Timesheet.DetailsClass.SetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Issues As Global.LightSwitchApplication.Issue
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Issues)
            End Get
            Set
                __Timesheet.DetailsClass.SetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Issues, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Issues_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Issues_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Issues_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Engineers As Global.LightSwitchApplication.Engineer
            Get
                Return __Timesheet.DetailsClass.GetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Engineers)
            End Get
            Set
                __Timesheet.DetailsClass.SetValue(Me, __Timesheet.DetailsClass.PropertySetProperties.Engineers, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Engineers_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Engineers_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Engineers_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Timesheet, _
                __Timesheet.DetailsClass, _
                __Timesheet.DetailsClass.IImplementation, _
                __Timesheet.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Timesheet, __Timesheet.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Timesheet, __Timesheet.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Timesheet.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __TimesheetEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Timesheet, __Timesheet.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Timesheet, __Timesheet.DetailsClass).Entry( _
                    AddressOf __Timesheet.DetailsClass.__Timesheet_CreateNew, _
                    AddressOf __Timesheet.DetailsClass.__Timesheet_Created, _
                    AddressOf __Timesheet.DetailsClass.__Timesheet_AllowSaveWithErrors)
            Private Shared Function __Timesheet_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Timesheet)) As __Timesheet
                Return New __Timesheet(es)
            End Function
            Private Shared Sub __Timesheet_Created(e As __Timesheet)
                e.Timesheet_Created()
            End Sub
            Private Shared Function __Timesheet_AllowSaveWithErrors(e As __Timesheet) As Boolean
                Dim result As Boolean = False
                e.Timesheet_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Timesheet, __Timesheet.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Timesheet, __Timesheet.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Timesheet.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Timesheet, __Timesheet.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property DurationMins As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.DurationMins),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.Issues),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue))
                    End Get
                End Property
                
                Public ReadOnly Property Engineers As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Timesheet.DetailsClass.PropertySetProperties.Engineers),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property DurationMins As Integer
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
                Shadows Property Issues As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property Engineers As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __Timesheet.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __Timesheet.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __Timesheet)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly DurationMins As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Entry( _
                        "DurationMins", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_GetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_SetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._DurationMins_OnValueChanged)
                Private Shared Sub _DurationMins_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._DurationMins, sf)
                End Sub
                Private Shared Function _DurationMins_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.DurationMins_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _DurationMins_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.DurationMins_Validate(r)
                End Sub
                Private Shared Function _DurationMins_GetImplementationValue(d As __Timesheet.DetailsClass) As Integer
                    Return d.ImplementationEntity.DurationMins
                End Function
                Private Shared Sub _DurationMins_SetImplementationValue(d As __Timesheet.DetailsClass, v As Integer)
                    d.ImplementationEntity.DurationMins = v
                End Sub
                Private Shared Sub _DurationMins_OnValueChanged(e As __Timesheet)
                    e.DurationMins_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __Timesheet.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __Timesheet)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __Timesheet.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __Timesheet)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __Timesheet.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __Timesheet)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __Timesheet.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __Timesheet)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte()).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __Timesheet.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __Timesheet.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __Timesheet)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue).Entry( _
                        "Issues", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_GetCoreImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_GetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_SetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_Refresh, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Issues_OnValueChanged)
                Private Shared Sub _Issues_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._Issues, sf)
                End Sub
                Private Shared Function _Issues_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.Issues_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Issues_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Issues_Validate(r)
                End Sub
                Private Shared Function _Issues_GetCoreImplementationValue(d as __Timesheet.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Issues
                End Function
                Private Shared Function _Issues_GetImplementationValue(d as __Timesheet.DetailsClass) As Global.LightSwitchApplication.Issue
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Issue, Global.LightSwitchApplication.Issue.DetailsClass)(__Timesheet.DetailsClass.PropertySetProperties.Issues, d._Issues)
                End Function
                Private Shared Sub _Issues_SetImplementationValue(d As __Timesheet.DetailsClass, v As Global.LightSwitchApplication.Issue)
                    d.SetImplementationValue(__Timesheet.DetailsClass.PropertySetProperties.Issues, d._Issues, Sub(i, ev) i.Issues = ev, v)
                End Sub
                Private Shared Sub _Issues_Refresh(d As __Timesheet.DetailsClass)
                    d.RefreshNavigationProperty(__Timesheet.DetailsClass.PropertySetProperties.Issues, d._Issues)
                End Sub
                Private Shared Sub _Issues_OnValueChanged(e As __Timesheet)
                    e.Issues_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Engineers As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer).Entry( _
                        "Engineers", _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_Stub, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_ComputeIsReadOnly, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_Validate, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_GetCoreImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_GetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_SetImplementationValue, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_Refresh, _
                        AddressOf __Timesheet.DetailsClass.PropertySetProperties._Engineers_OnValueChanged)
                Private Shared Sub _Engineers_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Timesheet.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer).Data), d As __Timesheet.DetailsClass, sf As Object)
                    c(d, d._Engineers, sf)
                End Sub
                Private Shared Function _Engineers_ComputeIsReadOnly(e As __Timesheet) As Boolean
                    Dim result As Boolean = False
                    e.Engineers_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Engineers_Validate(e As __Timesheet, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Engineers_Validate(r)
                End Sub
                Private Shared Function _Engineers_GetCoreImplementationValue(d as __Timesheet.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Engineers
                End Function
                Private Shared Function _Engineers_GetImplementationValue(d as __Timesheet.DetailsClass) As Global.LightSwitchApplication.Engineer
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Engineer, Global.LightSwitchApplication.Engineer.DetailsClass)(__Timesheet.DetailsClass.PropertySetProperties.Engineers, d._Engineers)
                End Function
                Private Shared Sub _Engineers_SetImplementationValue(d As __Timesheet.DetailsClass, v As Global.LightSwitchApplication.Engineer)
                    d.SetImplementationValue(__Timesheet.DetailsClass.PropertySetProperties.Engineers, d._Engineers, Sub(i, ev) i.Engineers = ev, v)
                End Sub
                Private Shared Sub _Engineers_Refresh(d As __Timesheet.DetailsClass)
                    d.RefreshNavigationProperty(__Timesheet.DetailsClass.PropertySetProperties.Engineers, d._Engineers)
                End Sub
                Private Shared Sub _Engineers_OnValueChanged(e As __Timesheet)
                    e.Engineers_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _DurationMins As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Timesheet, __Timesheet.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Issue).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Engineers As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Timesheet, __Timesheet.DetailsClass, Global.LightSwitchApplication.Engineer).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
