'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Client
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Client", GetType(Client).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure  you want to delete all issues older than 12 months?.
        '''</summary>
        Friend Shared ReadOnly Property ArchiveConfirmMessage() As String
            Get
                Return ResourceManager.GetString("ArchiveConfirmMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Delete.
        '''</summary>
        Friend Shared ReadOnly Property ArchiveConfirmTitle() As String
            Get
                Return ResourceManager.GetString("ArchiveConfirmTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create New Engineer.
        '''</summary>
        Friend Shared ReadOnly Property CreateNewEngineer() As String
            Get
                Return ResourceManager.GetString("CreateNewEngineer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create New Issue.
        '''</summary>
        Friend Shared ReadOnly Property CreateNewIssue() As String
            Get
                Return ResourceManager.GetString("CreateNewIssue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Engineers Grid.
        '''</summary>
        Friend Shared ReadOnly Property EditableEngineersGrid() As String
            Get
                Return ResourceManager.GetString("EditableEngineersGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Issues Grid.
        '''</summary>
        Friend Shared ReadOnly Property EditableIssuesGrid() As String
            Get
                Return ResourceManager.GetString("EditableIssuesGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Engineer.
        '''</summary>
        Friend Shared ReadOnly Property Engineer() As String
            Get
                Return ResourceManager.GetString("Engineer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issue.
        '''</summary>
        Friend Shared ReadOnly Property Issue() As String
            Get
                Return ResourceManager.GetString("Issue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tasks.
        '''</summary>
        Friend Shared ReadOnly Property Tasks() As String
            Get
                Return ResourceManager.GetString("Tasks", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
