

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class EngineerSkill : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EngineerSkill entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EngineerSkill()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EngineerSkill(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EngineerSkill> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EngineerSkill.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EngineerSkill_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EngineerSkill_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EngineerSkill.DetailsClass.SetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EngineerSkill.DetailsClass.SetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Engineer Engineer
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer);
            }
            set
            {
                global::LightSwitchApplication.EngineerSkill.DetailsClass.SetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Engineer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Engineer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Engineer_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Skill Skill
        {
            get
            {
                return global::LightSwitchApplication.EngineerSkill.DetailsClass.GetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill);
            }
            set
            {
                global::LightSwitchApplication.EngineerSkill.DetailsClass.SetValue(this, global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Skill_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Skill_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Skill_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EngineerSkill,
                global::LightSwitchApplication.EngineerSkill.DetailsClass,
                global::LightSwitchApplication.EngineerSkill.DetailsClass.IImplementation,
                global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>.Entry
                __EngineerSkillEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>.Entry(
                    global::LightSwitchApplication.EngineerSkill.DetailsClass.__EngineerSkill_CreateNew,
                    global::LightSwitchApplication.EngineerSkill.DetailsClass.__EngineerSkill_Created,
                    global::LightSwitchApplication.EngineerSkill.DetailsClass.__EngineerSkill_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EngineerSkill __EngineerSkill_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EngineerSkill> es)
            {
                return new global::LightSwitchApplication.EngineerSkill(es);
            }
            private static void __EngineerSkill_Created(global::LightSwitchApplication.EngineerSkill e)
            {
                e.EngineerSkill_Created();
            }
            private static bool __EngineerSkill_AllowSaveWithErrors(global::LightSwitchApplication.EngineerSkill e)
            {
                bool result = false;
                e.EngineerSkill_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer> Engineer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill> Skill
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Engineer { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Skill { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer>.Entry
                    Engineer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer>.Entry(
                        "Engineer",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_GetCoreImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_GetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_SetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_Refresh,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Engineer_OnValueChanged);
                private static void _Engineer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._Engineer, sf);
                }
                private static bool _Engineer_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.Engineer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Engineer_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Engineer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Engineer_GetCoreImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.Engineer;
                }
                private static global::LightSwitchApplication.Engineer _Engineer_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Engineer, global::LightSwitchApplication.Engineer.DetailsClass>(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer, ref d._Engineer);
                }
                private static void _Engineer_SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d, global::LightSwitchApplication.Engineer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer, ref d._Engineer, (i, ev) => i.Engineer = ev, v);
                }
                private static void _Engineer_Refresh(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Engineer, ref d._Engineer);
                }
                private static void _Engineer_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.Engineer_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill>.Entry
                    Skill = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill>.Entry(
                        "Skill",
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_Stub,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_ComputeIsReadOnly,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_Validate,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_GetCoreImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_GetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_SetImplementationValue,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_Refresh,
                        global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties._Skill_OnValueChanged);
                private static void _Skill_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EngineerSkill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill>.Data> c, global::LightSwitchApplication.EngineerSkill.DetailsClass d, object sf)
                {
                    c(d, ref d._Skill, sf);
                }
                private static bool _Skill_ComputeIsReadOnly(global::LightSwitchApplication.EngineerSkill e)
                {
                    bool result = false;
                    e.Skill_IsReadOnly(ref result);
                    return result;
                }
                private static void _Skill_Validate(global::LightSwitchApplication.EngineerSkill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Skill_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Skill_GetCoreImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.ImplementationEntity.Skill;
                }
                private static global::LightSwitchApplication.Skill _Skill_GetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill, ref d._Skill);
                }
                private static void _Skill_SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass d, global::LightSwitchApplication.Skill v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill, ref d._Skill, (i, ev) => i.Skill = ev, v);
                }
                private static void _Skill_Refresh(global::LightSwitchApplication.EngineerSkill.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EngineerSkill.DetailsClass.PropertySetProperties.Skill, ref d._Skill);
                }
                private static void _Skill_OnValueChanged(global::LightSwitchApplication.EngineerSkill e)
                {
                    e.Skill_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Engineer>.Data _Engineer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass, global::LightSwitchApplication.Skill>.Data _Skill;
            
        }
    
        #endregion
    }
    
    #endregion
}
