'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CreateNewEngineer = LightSwitchApplication.CreateNewEngineer
Imports __CreateNewIssue = LightSwitchApplication.CreateNewIssue
Imports __EditableEngineersGrid = LightSwitchApplication.EditableEngineersGrid
Imports __EditableIssuesGrid = LightSwitchApplication.EditableIssuesGrid
Imports __Info = LightSwitchApplication.Info

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class CreateNewEngineer
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication.HelpDeskVB.DesktopClient:CreateNewEngineer")
            __CreateNewEngineer.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As CreateNewEngineer
            Return New __CreateNewEngineer( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewEngineer_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub EngineerProperty_Changed()
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property EngineerProperty As Global.LightSwitchApplication.Engineer
            Get
                Return __CreateNewEngineer.DetailsClass.GetValue(Me, __CreateNewEngineer.DetailsClass.PropertySetProperties.EngineerProperty)
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Engineer)
                __CreateNewEngineer.DetailsClass.SetValue(Me, __CreateNewEngineer.DetailsClass.PropertySetProperties.EngineerProperty, value)
            End Set
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EngineerProperty_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, __CreateNewEngineer.DetailsClass.PropertySet, __CreateNewEngineer.DetailsClass.CommandSet, __CreateNewEngineer.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __CreateNewEngineer.DetailsClass.PropertySetProperties.EngineerProperty
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CreateNewEngineerEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass).Entry( _
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeInitializeDataWorkspace,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeSavingEvent,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeSavedEvent,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeClosingEvent,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeCreated,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeActivated,
                    AddressOf __CreateNewEngineer.DetailsClass.__CreateNewEngineer_InvokeSaveErrorEvent)
            Private Shared Sub __CreateNewEngineer_InvokeInitializeDataWorkspace(s As __CreateNewEngineer, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.CreateNewEngineer_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __CreateNewEngineer_InvokeSavingEvent(s As __CreateNewEngineer) As Boolean
                Dim handled = False
                s.CreateNewEngineer_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __CreateNewEngineer_InvokeSavedEvent(s As __CreateNewEngineer)
                s.CreateNewEngineer_Saved()
            End Sub
            Private Shared Function __CreateNewEngineer_InvokeClosingEvent(s As __CreateNewEngineer) As Boolean
                Dim cancel = False
                s.CreateNewEngineer_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __CreateNewEngineer_InvokeCreated(s As __CreateNewEngineer)
                s.CreateNewEngineer_Created()
            End Sub
            Private Shared Sub __CreateNewEngineer_InvokeActivated(s As __CreateNewEngineer)
                s.CreateNewEngineer_Activated()
            End Sub
            Private Shared Function __CreateNewEngineer_InvokeSaveErrorEvent(s As __CreateNewEngineer, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.CreateNewEngineer_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __CreateNewEngineer.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __CreateNewEngineer.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __CreateNewEngineer.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _EngineerProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, Global.LightSwitchApplication.Engineer).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass)

                Public ReadOnly Property EngineerProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, Global.LightSwitchApplication.Engineer)
                    Get
                        Return DirectCast(MyBase.GetItem(__CreateNewEngineer.DetailsClass.PropertySetProperties.EngineerProperty), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, Global.LightSwitchApplication.Engineer))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly EngineerProperty As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, Global.LightSwitchApplication.Engineer).Entry( _
                    "EngineerProperty",
                    False,
                    AddressOf __CreateNewEngineer.DetailsClass.PropertySetProperties._EngineerProperty_Stub,
                    AddressOf __CreateNewEngineer.DetailsClass.PropertySetProperties._EngineerProperty_Validate,
                    AddressOf __CreateNewEngineer.DetailsClass.PropertySetProperties._EngineerProperty_OnValueChanged)
                Private Shared Sub _EngineerProperty_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CreateNewEngineer.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewEngineer, __CreateNewEngineer.DetailsClass, Global.LightSwitchApplication.Engineer).Data), d As __CreateNewEngineer.DetailsClass, sf As Object)
                    c(d, d._EngineerProperty, sf)
                End Sub
                Private Shared Sub _EngineerProperty_Validate(s As __CreateNewEngineer, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.EngineerProperty_Validate(r)
                End Sub
                Private Shared Sub _EngineerProperty_OnValueChanged(s As __CreateNewEngineer)
                    s.EngineerProperty_Changed()
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class CreateNewIssue
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __CreateNewIssue, __CreateNewIssue.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication.HelpDeskVB.DesktopClient:CreateNewIssue")
            __CreateNewIssue.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As CreateNewIssue
            Return New __CreateNewIssue( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssue_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub IssueProperty_Changed()
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property IssueProperty As Global.LightSwitchApplication.Issue
            Get
                Return __CreateNewIssue.DetailsClass.GetValue(Me, __CreateNewIssue.DetailsClass.PropertySetProperties.IssueProperty)
            End Get
            Set(ByVal value As Global.LightSwitchApplication.Issue)
                __CreateNewIssue.DetailsClass.SetValue(Me, __CreateNewIssue.DetailsClass.PropertySetProperties.IssueProperty, value)
            End Set
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IssueProperty_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, __CreateNewIssue.DetailsClass.PropertySet, __CreateNewIssue.DetailsClass.CommandSet, __CreateNewIssue.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __CreateNewIssue.DetailsClass.PropertySetProperties.IssueProperty
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CreateNewIssueEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewIssue, __CreateNewIssue.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __CreateNewIssue, __CreateNewIssue.DetailsClass).Entry( _
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeInitializeDataWorkspace,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeSavingEvent,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeSavedEvent,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeClosingEvent,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeCreated,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeActivated,
                    AddressOf __CreateNewIssue.DetailsClass.__CreateNewIssue_InvokeSaveErrorEvent)
            Private Shared Sub __CreateNewIssue_InvokeInitializeDataWorkspace(s As __CreateNewIssue, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.CreateNewIssue_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __CreateNewIssue_InvokeSavingEvent(s As __CreateNewIssue) As Boolean
                Dim handled = False
                s.CreateNewIssue_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __CreateNewIssue_InvokeSavedEvent(s As __CreateNewIssue)
                s.CreateNewIssue_Saved()
            End Sub
            Private Shared Function __CreateNewIssue_InvokeClosingEvent(s As __CreateNewIssue) As Boolean
                Dim cancel = False
                s.CreateNewIssue_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __CreateNewIssue_InvokeCreated(s As __CreateNewIssue)
                s.CreateNewIssue_Created()
            End Sub
            Private Shared Sub __CreateNewIssue_InvokeActivated(s As __CreateNewIssue)
                s.CreateNewIssue_Activated()
            End Sub
            Private Shared Function __CreateNewIssue_InvokeSaveErrorEvent(s As __CreateNewIssue, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.CreateNewIssue_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __CreateNewIssue.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __CreateNewIssue.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __CreateNewIssue.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _IssueProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, Global.LightSwitchApplication.Issue).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __CreateNewIssue, __CreateNewIssue.DetailsClass)

                Public ReadOnly Property IssueProperty As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, Global.LightSwitchApplication.Issue)
                    Get
                        Return DirectCast(MyBase.GetItem(__CreateNewIssue.DetailsClass.PropertySetProperties.IssueProperty), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, Global.LightSwitchApplication.Issue))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __CreateNewIssue, __CreateNewIssue.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __CreateNewIssue, __CreateNewIssue.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly IssueProperty As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, Global.LightSwitchApplication.Issue).Entry( _
                    "IssueProperty",
                    False,
                    AddressOf __CreateNewIssue.DetailsClass.PropertySetProperties._IssueProperty_Stub,
                    AddressOf __CreateNewIssue.DetailsClass.PropertySetProperties._IssueProperty_Validate,
                    AddressOf __CreateNewIssue.DetailsClass.PropertySetProperties._IssueProperty_OnValueChanged)
                Private Shared Sub _IssueProperty_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CreateNewIssue.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty(Of __CreateNewIssue, __CreateNewIssue.DetailsClass, Global.LightSwitchApplication.Issue).Data), d As __CreateNewIssue.DetailsClass, sf As Object)
                    c(d, d._IssueProperty, sf)
                End Sub
                Private Shared Sub _IssueProperty_Validate(s As __CreateNewIssue, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.IssueProperty_Validate(r)
                End Sub
                Private Shared Sub _IssueProperty_OnValueChanged(s As __CreateNewIssue)
                    s.IssueProperty_Changed()
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class EditableEngineersGrid
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableEngineersGrid")
            __EditableEngineersGrid.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As EditableEngineersGrid
            Return New __EditableEngineersGrid( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub Engineers_SelectionChanged()
        End Sub

        Partial Private Sub Engineers_Changed(ByVal e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Engineers_Loaded(ByVal succeeded As Boolean)
        End Sub

        ''' <summary>
        ''' Gets the Engineers visual collection. The collection contains all records currently shown on the respective list or grid control.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Engineers As Global.Microsoft.LightSwitch.Framework.Client.VisualCollection(Of Global.LightSwitchApplication.Engineer)
            Get
                Return __EditableEngineersGrid.DetailsClass.GetValue(Me, __EditableEngineersGrid.DetailsClass.PropertySetProperties.Engineers)
            End Get
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Engineers_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, __EditableEngineersGrid.DetailsClass.PropertySet, __EditableEngineersGrid.DetailsClass.CommandSet, __EditableEngineersGrid.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __EditableEngineersGrid.DetailsClass.PropertySetProperties.Engineers
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __EditableEngineersGridEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass).Entry( _
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeInitializeDataWorkspace,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeSavingEvent,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeSavedEvent,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeClosingEvent,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeCreated,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeActivated,
                    AddressOf __EditableEngineersGrid.DetailsClass.__EditableEngineersGrid_InvokeSaveErrorEvent)
            Private Shared Sub __EditableEngineersGrid_InvokeInitializeDataWorkspace(s As __EditableEngineersGrid, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.EditableEngineersGrid_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __EditableEngineersGrid_InvokeSavingEvent(s As __EditableEngineersGrid) As Boolean
                Dim handled = False
                s.EditableEngineersGrid_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __EditableEngineersGrid_InvokeSavedEvent(s As __EditableEngineersGrid)
                s.EditableEngineersGrid_Saved()
            End Sub
            Private Shared Function __EditableEngineersGrid_InvokeClosingEvent(s As __EditableEngineersGrid) As Boolean
                Dim cancel = False
                s.EditableEngineersGrid_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __EditableEngineersGrid_InvokeCreated(s As __EditableEngineersGrid)
                s.EditableEngineersGrid_Created()
            End Sub
            Private Shared Sub __EditableEngineersGrid_InvokeActivated(s As __EditableEngineersGrid)
                s.EditableEngineersGrid_Activated()
            End Sub
            Private Shared Function __EditableEngineersGrid_InvokeSaveErrorEvent(s As __EditableEngineersGrid, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.EditableEngineersGrid_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __EditableEngineersGrid.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __EditableEngineersGrid.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __EditableEngineersGrid.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Private Function EngineersQuery() As Global.Microsoft.LightSwitch.IDataServiceQueryable
                Return Me.Screen.DataWorkspace.ApplicationData.Engineers
            End Function

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _Engineers As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, Global.LightSwitchApplication.Engineer).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass)

                Public ReadOnly Property Engineers As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, Global.LightSwitchApplication.Engineer)
                    Get
                        Return DirectCast(MyBase.GetItem(__EditableEngineersGrid.DetailsClass.PropertySetProperties.Engineers), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, Global.LightSwitchApplication.Engineer))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly Engineers As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, Global.LightSwitchApplication.Engineer).Entry( _
                    "Engineers",
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_Stub,
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_Validate,
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_CreateQuery,
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_SelectionChanged,
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_OnCollectionChanged,
                    AddressOf __EditableEngineersGrid.DetailsClass.PropertySetProperties._Engineers_OnLoaded)
                Private Shared Sub _Engineers_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EditableEngineersGrid.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableEngineersGrid, __EditableEngineersGrid.DetailsClass, Global.LightSwitchApplication.Engineer).Data), d As __EditableEngineersGrid.DetailsClass, sf As Object)
                    c(d, d._Engineers, sf)
                End Sub
                Private Shared Sub _Engineers_Validate(s As __EditableEngineersGrid, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.Engineers_Validate(r)
                End Sub
                Private Shared Function _Engineers_CreateQuery(d As __EditableEngineersGrid.DetailsClass, args As Object()) As Global.Microsoft.LightSwitch.IDataServiceQueryable
                    Return d.EngineersQuery()
                End Function
                Private Shared Sub _Engineers_SelectionChanged(s As __EditableEngineersGrid)
                    s.Engineers_SelectionChanged()
                End Sub
                Private Shared Sub _Engineers_OnCollectionChanged(s As __EditableEngineersGrid, e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
                    s.Engineers_Changed(e)
                End Sub
                Private Shared Sub _Engineers_OnLoaded(s As __EditableEngineersGrid, succeeded As Boolean)
                    s.Engineers_Loaded(succeeded)
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class EditableIssuesGrid
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableIssuesGrid")
            __EditableIssuesGrid.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As EditableIssuesGrid
            Return New __EditableIssuesGrid( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssuesGrid_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        Partial Private Sub Issues_SelectionChanged()
        End Sub

        Partial Private Sub Issues_Changed(ByVal e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Issues_Loaded(ByVal succeeded As Boolean)
        End Sub

        ''' <summary>
        ''' Gets the Issues visual collection. The collection contains all records currently shown on the respective list or grid control.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Issues As Global.Microsoft.LightSwitch.Framework.Client.VisualCollection(Of Global.LightSwitchApplication.Issue)
            Get
                Return __EditableIssuesGrid.DetailsClass.GetValue(Me, __EditableIssuesGrid.DetailsClass.PropertySetProperties.Issues)
            End Get
        End Property
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Issues_Validate(ByVal results As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
        End Sub
 
        ''' <summary>
        ''' Calls the Archive screen method.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub Archive()
            Me.Details.Methods.Archive.CreateInvocation().Execute()
        End Sub
        Partial Private Sub Archive_CanExecute(ByRef result As Boolean)
        End Sub
        Partial Private Sub Archive_Execute()
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, __EditableIssuesGrid.DetailsClass.PropertySet, __EditableIssuesGrid.DetailsClass.CommandSet, __EditableIssuesGrid.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializePropertyEntry = __EditableIssuesGrid.DetailsClass.PropertySetProperties.Issues
                Dim initializeCommandEntry = __EditableIssuesGrid.DetailsClass.CommandSetProperties.Archive
                Dim initializeMethodEntry = __EditableIssuesGrid.DetailsClass.MethodSetProperties.Archive
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __EditableIssuesGridEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Entry( _
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeInitializeDataWorkspace,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeSavingEvent,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeSavedEvent,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeClosingEvent,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeCreated,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeActivated,
                    AddressOf __EditableIssuesGrid.DetailsClass.__EditableIssuesGrid_InvokeSaveErrorEvent)
            Private Shared Sub __EditableIssuesGrid_InvokeInitializeDataWorkspace(s As __EditableIssuesGrid, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.EditableIssuesGrid_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __EditableIssuesGrid_InvokeSavingEvent(s As __EditableIssuesGrid) As Boolean
                Dim handled = False
                s.EditableIssuesGrid_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __EditableIssuesGrid_InvokeSavedEvent(s As __EditableIssuesGrid)
                s.EditableIssuesGrid_Saved()
            End Sub
            Private Shared Function __EditableIssuesGrid_InvokeClosingEvent(s As __EditableIssuesGrid) As Boolean
                Dim cancel = False
                s.EditableIssuesGrid_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __EditableIssuesGrid_InvokeCreated(s As __EditableIssuesGrid)
                s.EditableIssuesGrid_Created()
            End Sub
            Private Shared Sub __EditableIssuesGrid_InvokeActivated(s As __EditableIssuesGrid)
                s.EditableIssuesGrid_Activated()
            End Sub
            Private Shared Function __EditableIssuesGrid_InvokeSaveErrorEvent(s As __EditableIssuesGrid, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.EditableIssuesGrid_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __EditableIssuesGrid.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __EditableIssuesGrid.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __EditableIssuesGrid.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Private Function IssuesQuery() As Global.Microsoft.LightSwitch.IDataServiceQueryable
                Return Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                    Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                        Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                            Global.Microsoft.LightSwitch.DataServiceQueryable.Include(
                                Me.Screen.DataWorkspace.ApplicationData.Issues,
                                "AssignedEngineer"),
                            "ClosedByEngineer"),
                        "Priority"),
                    "IssueStatus")
            End Function

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _Issues As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, Global.LightSwitchApplication.Issue).Data

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _ArchiveCommand As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Data

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)>
            Private _ArchiveMethod As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Data

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)

                Public ReadOnly Property Issues As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, Global.LightSwitchApplication.Issue)
                    Get
                        Return DirectCast(MyBase.GetItem(__EditableIssuesGrid.DetailsClass.PropertySetProperties.Issues), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, Global.LightSwitchApplication.Issue))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)

                Public ReadOnly Property Archive As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(__EditableIssuesGrid.DetailsClass.CommandSetProperties.Archive), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)

                Public ReadOnly Property Archive As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(__EditableIssuesGrid.DetailsClass.MethodSetProperties.Archive), Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

                Public Shared ReadOnly Issues As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, Global.LightSwitchApplication.Issue).Entry( _
                    "Issues",
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_Stub,
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_Validate,
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_CreateQuery,
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_SelectionChanged,
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_OnCollectionChanged,
                    AddressOf __EditableIssuesGrid.DetailsClass.PropertySetProperties._Issues_OnLoaded)
                Private Shared Sub _Issues_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EditableIssuesGrid.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass, Global.LightSwitchApplication.Issue).Data), d As __EditableIssuesGrid.DetailsClass, sf As Object)
                    c(d, d._Issues, sf)
                End Sub
                Private Shared Sub _Issues_Validate(s As __EditableIssuesGrid, r As Global.Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder)
                    s.Issues_Validate(r)
                End Sub
                Private Shared Function _Issues_CreateQuery(d As __EditableIssuesGrid.DetailsClass, args As Object()) As Global.Microsoft.LightSwitch.IDataServiceQueryable
                    Return d.IssuesQuery()
                End Function
                Private Shared Sub _Issues_SelectionChanged(s As __EditableIssuesGrid)
                    s.Issues_SelectionChanged()
                End Sub
                Private Shared Sub _Issues_OnCollectionChanged(s As __EditableIssuesGrid, e As Global.System.Collections.Specialized.NotifyCollectionChangedEventArgs)
                    s.Issues_Changed(e)
                End Sub
                Private Shared Sub _Issues_OnLoaded(s As __EditableIssuesGrid, succeeded As Boolean)
                    s.Issues_Loaded(succeeded)
                End Sub

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties

                Public Shared ReadOnly Archive As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Entry( _
                    "Archive",
                    AddressOf __EditableIssuesGrid.DetailsClass.CommandSetProperties._Archive_Stub,
                    AddressOf __EditableIssuesGrid.DetailsClass.CommandSetProperties._Archive_CreateExecutableObject)
                Private Shared Sub _Archive_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EditableIssuesGrid.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Data), d As __EditableIssuesGrid.DetailsClass, sf As Object)
                    c(d, d._ArchiveCommand, sf)
                End Sub
                Private Shared Function _Archive_CreateExecutableObject(d As __EditableIssuesGrid.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, __EditableIssuesGrid.DetailsClass).Methods.Archive.CreateInvocation()
                End Function

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties

                Public Shared ReadOnly Archive As New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Entry( _
                    "Archive",
                    AddressOf __EditableIssuesGrid.DetailsClass.MethodSetProperties._Archive_Stub,
                    AddressOf __EditableIssuesGrid.DetailsClass.MethodSetProperties._Archive_CanInvoke,
                    AddressOf __EditableIssuesGrid.DetailsClass.MethodSetProperties._Archive_InvokeMethod)
                Private Shared Sub _Archive_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EditableIssuesGrid.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod(Of __EditableIssuesGrid, __EditableIssuesGrid.DetailsClass).Data), d As __EditableIssuesGrid.DetailsClass, sf As Object)
                    c(d, d._ArchiveMethod, sf)
                End Sub
                Private Shared Function _Archive_CanInvoke(d As __EditableIssuesGrid.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result = True
                    d.Screen.Archive_CanExecute(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _Archive_InvokeMethod(d As __EditableIssuesGrid.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    d.Screen.Archive_Execute()
                End Sub

            End Class

        End Class

    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class Info
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ScreenObject(Of __Info, __Info.DetailsClass)

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private Sub New()
            MyBase.New("LightSwitchApplication.HelpDeskVB.DesktopClient:Info")
            __Info.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Public Shared Function CreateInstance() As Info
            Return New __Info( _
            )
        End Function

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_InitializeDataWorkspace(ByVal saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_Activated()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_Saving(ByRef handled As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_Saved()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_Closing(ByRef cancel As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Info_SaveError(ByVal exception As Global.System.Exception, ByRef handled As Boolean)
        End Sub
     
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IScreenDetails).DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
 
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __Info, __Info.DetailsClass, __Info.DetailsClass.PropertySet, __Info.DetailsClass.CommandSet, __Info.DetailsClass.MethodSet)

            Shared Sub New()
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __InfoEntry As Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __Info, __Info.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails(Of __Info, __Info.DetailsClass).Entry( _
                    AddressOf __Info.DetailsClass.__Info_InvokeInitializeDataWorkspace,
                    AddressOf __Info.DetailsClass.__Info_InvokeSavingEvent,
                    AddressOf __Info.DetailsClass.__Info_InvokeSavedEvent,
                    AddressOf __Info.DetailsClass.__Info_InvokeClosingEvent,
                    AddressOf __Info.DetailsClass.__Info_InvokeCreated,
                    AddressOf __Info.DetailsClass.__Info_InvokeActivated,
                    AddressOf __Info.DetailsClass.__Info_InvokeSaveErrorEvent)
            Private Shared Sub __Info_InvokeInitializeDataWorkspace(s As __Info, saveChangesTo As Global.System.Collections.Generic.List(Of Global.Microsoft.LightSwitch.IDataService))
                s.Info_InitializeDataWorkspace(saveChangesTo)
            End Sub
            Private Shared Function __Info_InvokeSavingEvent(s As __Info) As Boolean
                Dim handled = False
                s.Info_Saving(handled)
                Return handled
            End Function
            Private Shared Sub __Info_InvokeSavedEvent(s As __Info)
                s.Info_Saved()
            End Sub
            Private Shared Function __Info_InvokeClosingEvent(s As __Info) As Boolean
                Dim cancel = False
                s.Info_Closing(cancel)
                Return cancel
            End Function
            Private Shared Sub __Info_InvokeCreated(s As __Info)
                s.Info_Created()
            End Sub
            Private Shared Sub __Info_InvokeActivated(s As __Info)
                s.Info_Activated()
            End Sub
            Private Shared Function __Info_InvokeSaveErrorEvent(s As __Info, ex As Global.System.Exception) As Boolean
                Dim handled = False
                s.Info_SaveError(ex, handled)
                Return handled
            End Function

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As __Info.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As __Info.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As __Info.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet(Of __Info, __Info.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet(Of __Info, __Info.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet(Of __Info, __Info.DetailsClass)
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties
            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties
            End Class

        End Class

    End Class

End Namespace
