


'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Partial Public NotInheritable Class Application
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.DataWorkspace)

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(ByVal applicationDefinition As Global.Microsoft.LightSwitch.Model.IApplicationDefinition)
            MyBase.New(applicationDefinition)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Application_Initialize()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Application_LoggedIn()
        End Sub

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Shared Shadows ReadOnly Property Current As Global.LightSwitchApplication.Application
            Get
                Return DirectCast(Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Current, Global.LightSwitchApplication.Application)
            End Get
        End Property

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppOptionsEdit_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AppOptionsEdit_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowAppOptionsEdit screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowAppOptionsEdit()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowAppOptionsEdit)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssueDocument_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreateNewIssueDocument_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowCreateNewIssueDocument screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowCreateNewIssueDocument()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowCreateNewIssueDocument)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableEngineersGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableEngineersGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableEngineersGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableEngineersGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssueDocumentsGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssueDocumentsGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableIssueDocumentsGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableIssueDocumentsGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableIssueDocumentsGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssueStatusSetGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableIssueStatusSetGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableIssueStatusSetGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableIssueStatusSetGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableIssueStatusSetGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditablePrioritiesGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditablePrioritiesGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditablePrioritiesGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditablePrioritiesGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditablePrioritiesGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableTimesheetsGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableTimesheetsGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableTimesheetsGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableTimesheetsGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableTimesheetsGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EngineerDetail_CanRun(ByRef result As Boolean, ByVal EngineerId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EngineerDetail_Run(ByRef handled As Boolean, ByVal EngineerId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEngineerDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEngineerDetail(ByVal EngineerId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEngineerDetail, EngineerId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EngineersListDetail_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EngineersListDetail_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEngineersListDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEngineersListDetail()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEngineersListDetail)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IssueDocumentDetail_CanRun(ByRef result As Boolean, ByVal IssueDocumentId As Integer)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IssueDocumentDetail_Run(ByRef handled As Boolean, ByVal IssueDocumentId As Integer)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowIssueDocumentDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowIssueDocumentDetail(ByVal IssueDocumentId As Integer)
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowIssueDocumentDetail, IssueDocumentId)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IssuesListDetail_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub IssuesListDetail_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowIssuesListDetail screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowIssuesListDetail()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowIssuesListDetail)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Startup_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Startup_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens a new instance of the ShowStartup screen.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowStartup()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowStartup)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.Application.DetailsClass.PropertySet, Global.LightSwitchApplication.Application.DetailsClass.CommandSet, Global.LightSwitchApplication.Application.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializeCommandEntry = Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowAppOptionsEdit
                Dim initializeMethodEntry = Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowAppOptionsEdit
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ApplicationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_Initialized, _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_LoggedIn)
            Private Shared Sub __Application_Initialized(a As Global.LightSwitchApplication.Application)
                a.Application_Initialize()
            End Sub
            Private Shared Sub __Application_LoggedIn(a As Global.LightSwitchApplication.Application)
                a.Application_LoggedIn()
            End Sub

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As Global.LightSwitchApplication.Application.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As Global.LightSwitchApplication.Application.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As Global.LightSwitchApplication.Application.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Protected Overrides Function CreateScreen(ByVal screenName As String, ByVal ParamArray args() As Object) As Global.Microsoft.LightSwitch.Client.IScreenObject
                Select Case screenName
                    Case "AppOptionsEdit"
                        Return Global.LightSwitchApplication.AppOptionsEdit.CreateInstance()
                    Case "CreateNewIssueDocument"
                        Return Global.LightSwitchApplication.CreateNewIssueDocument.CreateInstance()
                    Case "EditableEngineersGrid"
                        Return Global.LightSwitchApplication.EditableEngineersGrid.CreateInstance()
                    Case "EditableIssueDocumentsGrid"
                        Return Global.LightSwitchApplication.EditableIssueDocumentsGrid.CreateInstance()
                    Case "EditableIssueStatusSetGrid"
                        Return Global.LightSwitchApplication.EditableIssueStatusSetGrid.CreateInstance()
                    Case "EditablePrioritiesGrid"
                        Return Global.LightSwitchApplication.EditablePrioritiesGrid.CreateInstance()
                    Case "EditableTimesheetsGrid"
                        Return Global.LightSwitchApplication.EditableTimesheetsGrid.CreateInstance()
                    Case "EngineerDetail"
                        Return Global.LightSwitchApplication.EngineerDetail.CreateInstance(CType(args(0), Integer))
                    Case "EngineersListDetail"
                        Return Global.LightSwitchApplication.EngineersListDetail.CreateInstance()
                    Case "IssueDocumentDetail"
                        Return Global.LightSwitchApplication.IssueDocumentDetail.CreateInstance(CType(args(0), Integer))
                    Case "IssuesListDetail"
                        Return Global.LightSwitchApplication.IssuesListDetail.CreateInstance()
                    Case "Startup"
                        Return Global.LightSwitchApplication.Startup.CreateInstance()
                End Select
            
                Return MyBase.CreateScreen(screenName, args)
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationPropertySet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationCommandSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowAppOptionsEdit As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowAppOptionsEdit), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewIssueDocument As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowCreateNewIssueDocument), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableEngineersGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableEngineersGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableIssueDocumentsGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableIssueDocumentsGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableIssueStatusSetGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableIssueStatusSetGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditablePrioritiesGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditablePrioritiesGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableTimesheetsGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableTimesheetsGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEngineersListDetail As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEngineersListDetail), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowIssuesListDetail As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowIssuesListDetail), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowStartup As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowStartup), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationMethodSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowAppOptionsEdit As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowAppOptionsEdit), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowCreateNewIssueDocument As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowCreateNewIssueDocument), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableEngineersGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableEngineersGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableIssueDocumentsGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableIssueDocumentsGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableIssueStatusSetGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableIssueStatusSetGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditablePrioritiesGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditablePrioritiesGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableTimesheetsGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableTimesheetsGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEngineerDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEngineerDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEngineersListDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEngineersListDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowIssueDocumentDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowIssueDocumentDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowIssuesListDetail As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowIssuesListDetail), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowStartup As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowStartup), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties

                Public Shared ReadOnly ShowAppOptionsEdit As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowAppOptionsEdit",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowAppOptionsEdit_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowAppOptionsEdit_CreateExecutableObject)
                Private Shared Sub _ShowAppOptionsEdit_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowAppOptionsEditCommand, sf)
                End Sub
                Private Shared Function _ShowAppOptionsEdit_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowAppOptionsEdit.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowCreateNewIssueDocument As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewIssueDocument",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewIssueDocument_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowCreateNewIssueDocument_CreateExecutableObject)
                Private Shared Sub _ShowCreateNewIssueDocument_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewIssueDocumentCommand, sf)
                End Sub
                Private Shared Function _ShowCreateNewIssueDocument_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowCreateNewIssueDocument.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableEngineersGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableEngineersGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableEngineersGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableEngineersGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableEngineersGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableEngineersGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableEngineersGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableEngineersGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableIssueDocumentsGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableIssueDocumentsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableIssueDocumentsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableIssueDocumentsGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableIssueDocumentsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableIssueDocumentsGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableIssueDocumentsGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableIssueDocumentsGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableIssueStatusSetGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableIssueStatusSetGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableIssueStatusSetGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableIssueStatusSetGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableIssueStatusSetGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableIssueStatusSetGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableIssueStatusSetGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableIssueStatusSetGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditablePrioritiesGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditablePrioritiesGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditablePrioritiesGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditablePrioritiesGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditablePrioritiesGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditablePrioritiesGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditablePrioritiesGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditablePrioritiesGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableTimesheetsGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableTimesheetsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableTimesheetsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableTimesheetsGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableTimesheetsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableTimesheetsGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableTimesheetsGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableTimesheetsGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEngineersListDetail As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEngineersListDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEngineersListDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEngineersListDetail_CreateExecutableObject)
                Private Shared Sub _ShowEngineersListDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEngineersListDetailCommand, sf)
                End Sub
                Private Shared Function _ShowEngineersListDetail_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEngineersListDetail.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowIssuesListDetail As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowIssuesListDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowIssuesListDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowIssuesListDetail_CreateExecutableObject)
                Private Shared Sub _ShowIssuesListDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowIssuesListDetailCommand, sf)
                End Sub
                Private Shared Function _ShowIssuesListDetail_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowIssuesListDetail.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowStartup As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowStartup",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowStartup_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowStartup_CreateExecutableObject)
                Private Shared Sub _ShowStartup_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowStartupCommand, sf)
                End Sub
                Private Shared Function _ShowStartup_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowStartup.CreateInvocation(New Object(0 - 1) { })
                End Function

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties

                Public Shared ReadOnly ShowAppOptionsEdit As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowAppOptionsEdit",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppOptionsEdit_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppOptionsEdit_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowAppOptionsEdit_InvokeMethod)
                Private Shared Sub _ShowAppOptionsEdit_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowAppOptionsEditMethod, sf)
                End Sub
                Private Shared Function _ShowAppOptionsEdit_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.AppOptionsEdit_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowAppOptionsEdit_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.AppOptionsEdit_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:AppOptionsEdit", Function() Global.LightSwitchApplication.AppOptionsEdit.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowCreateNewIssueDocument As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowCreateNewIssueDocument",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewIssueDocument_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewIssueDocument_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowCreateNewIssueDocument_InvokeMethod)
                Private Shared Sub _ShowCreateNewIssueDocument_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowCreateNewIssueDocumentMethod, sf)
                End Sub
                Private Shared Function _ShowCreateNewIssueDocument_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.CreateNewIssueDocument_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowCreateNewIssueDocument_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.CreateNewIssueDocument_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:CreateNewIssueDocument", Function() Global.LightSwitchApplication.CreateNewIssueDocument.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableEngineersGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableEngineersGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableEngineersGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableEngineersGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableEngineersGrid_InvokeMethod)
                Private Shared Sub _ShowEditableEngineersGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableEngineersGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableEngineersGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableEngineersGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableEngineersGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableEngineersGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableEngineersGrid", Function() Global.LightSwitchApplication.EditableEngineersGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableIssueDocumentsGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableIssueDocumentsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueDocumentsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueDocumentsGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueDocumentsGrid_InvokeMethod)
                Private Shared Sub _ShowEditableIssueDocumentsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableIssueDocumentsGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableIssueDocumentsGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableIssueDocumentsGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableIssueDocumentsGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableIssueDocumentsGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableIssueDocumentsGrid", Function() Global.LightSwitchApplication.EditableIssueDocumentsGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableIssueStatusSetGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableIssueStatusSetGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueStatusSetGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueStatusSetGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableIssueStatusSetGrid_InvokeMethod)
                Private Shared Sub _ShowEditableIssueStatusSetGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableIssueStatusSetGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableIssueStatusSetGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableIssueStatusSetGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableIssueStatusSetGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableIssueStatusSetGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableIssueStatusSetGrid", Function() Global.LightSwitchApplication.EditableIssueStatusSetGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditablePrioritiesGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditablePrioritiesGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditablePrioritiesGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditablePrioritiesGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditablePrioritiesGrid_InvokeMethod)
                Private Shared Sub _ShowEditablePrioritiesGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditablePrioritiesGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditablePrioritiesGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditablePrioritiesGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditablePrioritiesGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditablePrioritiesGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EditablePrioritiesGrid", Function() Global.LightSwitchApplication.EditablePrioritiesGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableTimesheetsGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableTimesheetsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableTimesheetsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableTimesheetsGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableTimesheetsGrid_InvokeMethod)
                Private Shared Sub _ShowEditableTimesheetsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableTimesheetsGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableTimesheetsGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableTimesheetsGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableTimesheetsGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableTimesheetsGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EditableTimesheetsGrid", Function() Global.LightSwitchApplication.EditableTimesheetsGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEngineerDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEngineerDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineerDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineerDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineerDetail_InvokeMethod)
                Private Shared Sub _ShowEngineerDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEngineerDetailMethod, sf)
                End Sub
                Private Shared Function _ShowEngineerDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EngineerDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEngineerDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EngineerDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EngineerDetail", Function() Global.LightSwitchApplication.EngineerDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEngineersListDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEngineersListDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineersListDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineersListDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEngineersListDetail_InvokeMethod)
                Private Shared Sub _ShowEngineersListDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEngineersListDetailMethod, sf)
                End Sub
                Private Shared Function _ShowEngineersListDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EngineersListDetail_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEngineersListDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EngineersListDetail_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:EngineersListDetail", Function() Global.LightSwitchApplication.EngineersListDetail.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowIssueDocumentDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowIssueDocumentDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssueDocumentDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssueDocumentDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssueDocumentDetail_InvokeMethod)
                Private Shared Sub _ShowIssueDocumentDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowIssueDocumentDetailMethod, sf)
                End Sub
                Private Shared Function _ShowIssueDocumentDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.IssueDocumentDetail_CanRun(result, CType(args(0), Integer))
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowIssueDocumentDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.IssueDocumentDetail_Run(handled, CType(args(0), Integer))
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:IssueDocumentDetail", Function() Global.LightSwitchApplication.IssueDocumentDetail.CreateInstance(CType(args(0), Integer)), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowIssuesListDetail As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowIssuesListDetail",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssuesListDetail_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssuesListDetail_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowIssuesListDetail_InvokeMethod)
                Private Shared Sub _ShowIssuesListDetail_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowIssuesListDetailMethod, sf)
                End Sub
                Private Shared Function _ShowIssuesListDetail_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.IssuesListDetail_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowIssuesListDetail_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.IssuesListDetail_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:IssuesListDetail", Function() Global.LightSwitchApplication.IssuesListDetail.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowStartup As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowStartup",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowStartup_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowStartup_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowStartup_InvokeMethod)
                Private Shared Sub _ShowStartup_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowStartupMethod, sf)
                End Sub
                Private Shared Function _ShowStartup_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.Startup_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowStartup_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.Startup_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication.HelpDeskVB.DesktopClient:Startup", Function() Global.LightSwitchApplication.Startup.CreateInstance(), args)
                    End If
                End Sub
 
            End Class

            Private _ShowAppOptionsEditMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewIssueDocumentMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableEngineersGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableIssueDocumentsGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableIssueStatusSetGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditablePrioritiesGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableTimesheetsGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEngineerDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEngineersListDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowIssueDocumentDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowIssuesListDetailMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowStartupMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowAppOptionsEditCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowCreateNewIssueDocumentCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableEngineersGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableIssueDocumentsGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableIssueStatusSetGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditablePrioritiesGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableTimesheetsGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEngineersListDetailCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowIssuesListDetailCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowStartupCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

        End Class

    End Class

    <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> 
    <Global.System.Diagnostics.DebuggerNonUserCode> 
    <Global.System.CodeDom.Compiler.GeneratedCode("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")>
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader))> 
    <Global.Microsoft.LightSwitch.Model.ModuleDefinitionLoader("LightSwitchApplication.HelpDeskVB.DesktopClient")>
    Public Class ClientModuleLoader
        Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader
    
        Private resourceManagerChecked As Global.System.Boolean
        Private resourceManager As Global.System.Resources.ResourceManager
    
        Public Function GetModelResourceManager() As Global.System.Resources.ResourceManager Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.GetModelResourceManager
            If resourceManagerChecked = False Then
                Dim assembly As Global.System.Reflection.Assembly = Global.System.Reflection.Assembly.GetExecutingAssembly()
    
                For Each resourceName As Global.System.String In assembly.GetManifestResourceNames()
                    If resourceName.EndsWith("Client.resources", Global.System.StringComparison.OrdinalIgnoreCase) Then
                        Dim resxName As Global.System.String = resourceName.Substring(0, resourceName.Length - ".resources".Length)
                        resourceManager = new Global.System.Resources.ResourceManager(resxName, assembly)
                        Exit For
                    End If
                Next
                resourceManagerChecked = True
            End If
    
            Return resourceManager
        End Function
    
        Public Function LoadModelFragments() As Global.System.Collections.Generic.IEnumerable(Of Global.System.IO.Stream) Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.LoadModelFragments
            Dim assembly As Global.System.Reflection.Assembly = Global.System.Reflection.Assembly.GetExecutingAssembly()
            Dim streams As New Global.System.Collections.Generic.List(Of Global.System.IO.Stream)
    
            For Each resourceName As Global.System.String In assembly.GetManifestResourceNames
                If resourceName.EndsWith(".lsml", Global.System.StringComparison.OrdinalIgnoreCase) Then
                    streams.Add(assembly.GetManifestResourceStream(resourceName))
                End If
            Next
    
            Return streams
        End Function
    End Class
End Namespace
